// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icarvzzkfjcukdsoxrur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljYXJ2enprZmpjdWtkc294cnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTM1OTAsImV4cCI6MjA2OTUyOTU5MH0.ah4tpWQG7SybVdP6IRyc84E3Nc_WeiBdzpT7z-Va2Fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});